### ISSUE TITLE
assign parition number in kuberntes

### ISSUE THREAD

**Issue by mehran-prs** [liftbridge-io/go-liftbridge#103]
How should we assign partition numbers in Kubernetes which has multiple pods of our program and each pod should get a partition number?

**Comment by tylertreat** [comment]
Are you referring to partitioning rolling updates for StatefulSets in Kubernetes or something else?

**Comment by mehran-prs** [comment]
no, I mean I deploy my app to Kubernetes (using deployment) with three replicas, now I have three running instance of my app.
Let say I have a subject named "order.created" with 4 partitions, so we need to subscribe to these 4 partitions, how should I detect partition number to subject in each instance?

**Comment by tylertreat** [comment]
Stream partition assignments are automatically managed by the Liftbridge cluster. The client should just subscribe to, e.g. "order.created, partition 2" and the Go client library will resolve which node in the cluster is the leader of this partition and make the subscribe request to this node.

**Comment by mehran-prs** [comment]
Thank @tylertreat, but I mean something like consumerGroup, to do not set partition number explicitly.

**Comment by tylertreat** [comment]
I understand now. Consumer group functionality is still in development (see [roadmap](https://liftbridge.io/docs/roadmap.html#consumer-groups-46httpsgithubcomliftbridge-ioliftbridgeissues46)). Until then, you must manually assign partitions to consumers.
