### ISSUE TITLE
how to durable subscription 

### ISSUE THREAD

**Issue by Huangsir** [liftbridge-io/go-liftbridge#108]
how to durable position in subscription?

**Comment by tylertreat** [comment]
You need to use [`SetCursor` and `FetchCursor`](https://github.com/liftbridge-io/go-liftbridge/blob/dcbc40c4579a0929e243d2dd38eaafa5a49bf3f6/v2/client.go#L502-L509) to store/review consumer position.

One consumer groups are implemented this will be handled transparently.

**Comment by Huangsir** [comment]
it seems that SetCursor and FetchCursor not exist in v2

**Comment by tylertreat** [comment]
A new release of v2 needs to be made, but in the meantime you can pin against a specific commit.
