### ISSUE TITLE
Build instructions are out of date

### ISSUE THREAD

**Issue by justinfx** [liftbridge-io/go-liftbridge#2]
I just tried to `go get` the client as per the README and had trouble with protoc:

```
$ go get github.com/liftbridge-io/go-liftbridge 
# google.golang.org/genproto/googleapis/rpc/status
$GOPATH/src/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:111:28: undefined: proto.InternalMessageInfo

$ go generate github.com/liftbridge-io/go-liftbridge
liftbridge-grpc/api.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
$GOPATH/src/github.com/liftbridge-io/go-liftbridge/client.go:1: running "protoc": exit status 1

$ protoc --version
libprotoc 2.6.1
```

Seems the README is a little outdated, and this project requires protobuf v3 to be installed, as opposed to being go-gettable?

**Comment by tylertreat** [comment]
Interesting, I'm not able to reproduce that problem even installing from a clean Docker container. You generally should not need to generate the protobufs except for development purposes, in which case you do want proto3:

```
$ brew update
$ brew install protobuf
$ protoc --version
libprotoc 3.6.0
```

The genproto `status` package is [pre-generated by Google](https://github.com/google/go-genproto) and is a [dependency of grpc](https://godoc.org/google.golang.org/grpc/status?imports), so I'm not sure why `go get` is not pulling that down for you. In any case, it can be installed with:

```
$ go get google.golang.org/genproto/googleapis/rpc/...
```

Out of curiosity, what version of Go are you using?

```
$ go version
go version go1.10.3 darwin/amd64
```

**Comment by justinfx** [comment]
Ah nevermind. I had an out-of-date grpc, so a `go get -u` ended up working. Sorry for the noise.
