### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by anisbhsl** [liftbridge-io/go-liftbridge#37]
While trying to install ```go-liftbridge``` using
```
go get github.com/liftbridge-io/go-liftbridge
```

This is showing following error:
```
# github.com/liftbridge-io/go-liftbridge
../github.com/liftbridge-io/go-liftbridge/client.go:524:31: unknown field 'Message' in struct literal of type "github.com/liftbridge-io/liftbridge-api/go".PublishRequest
```
I think the problem is due to the ```PublishRequest``` type defined in  ```github.com/liftbridge-io/liftbridge-api/go``` is different from what ```client.go``` is using.

**Comment by tylertreat** [comment]
Yeah, there are some breaking API changes coming in preparation of a 1.0 release, so unfortunately _master_ is currently in an inconsistent state across go-liftbridge and liftbridge-api. To account for this in the meantime, there is a stable v0.0.1-alpha tag for go-liftbridge, liftbridge-api, and liftbridge. Try this:

```
go get github.com/liftbridge-io/go-liftbridge@v0.0.1-alpha
```

This requires using Go modules, which you might need to enable first:

```
export GO111MODULE=on
```

**Comment by anisbhsl** [comment]
Thanks! 
I have another question:

When shall we expect v1.0 release? v0.0.1-alpha seems to non-production release.

**Comment by tylertreat** [comment]
Shooting for a 1.0 release in March.

**Comment by paambaati** [comment]
@tylertreat If you don’t mind me asking here, has there been progress on the Flatbuffers move? Is 1.0 going to be built on gRPC or Flatbuffers?

**Comment by tylertreat** [comment]
1.0 is going to remain with gRPC and protobuf.
