### ISSUE TITLE
example needs NATS ?

### ISSUE THREAD

**Issue by gedw99** [liftbridge-io/go-liftbridge#4]
This may be a silly question but i had presumed that the clients would not need an import of nats, because GRPC is the only transport needed.
Maybe i have misunderstood ?

For example: https://github.com/liftbridge-io/go-liftbridge/blob/master/example/lift-pub/publish.go#L9
Why is the NATS import there ?

**Comment by tylertreat** [comment]
Because messages are still published to NATS. Liftbridge is just the
"journal". I've thought about exposing a publish API in Liftbridge that
would basically proxy NATS. That way clients could both publish and consume
via Liftbridge. That would be especially nice with the embedded mode.

**Comment by gedw99** [comment]
got ya. 

Yeah proxying NATS is exactly what i was after also. I think it would be great with embedded.
Then also full security control through the proxy.

**Comment by tylertreat** [comment]
Agreed, feel free to open an issue on the liftbridge repo to discuss a publish API.

**Comment by gedw99** [comment]
ok yes will do it there. closing
