### ISSUE TITLE
Subscribe hangs

### ISSUE THREAD

**Issue by ehsannm** [liftbridge-io/go-liftbridge#62]
If we subscribe with offsetID > stream.lastOffsetID,  the liftbridge.Handler is called with 'err' argument set to EOF. However I thinks it must wait until new message arrives. This should the caller to handle timeout. This way we improve the need for checking for subscribe on fast intervals by handling a longer timeout.

**Comment by tylertreat** [comment]
I'm not sure I understand. Can you provide the configuration and steps to reproduce the behavior you're seeing?

**Comment by ehsannm** [comment]
nothing i was using the context with timeout on Subscribe which was the problem. I close the issue
