### ISSUE TITLE
Improvement: allow overriding a host for standalone-dev image.

### ISSUE THREAD

**Issue by ruseinov** [liftbridge-io/go-liftbridge#68]
Hello @tylertreat! 

I'm trying to test the Rust client I'm currently working on, but the issue is that I don't run my docker host on localhost (docker-machine). 
And the `LIFTBRIDGE_HOST` env variable does not seem to have any effect as there is no default config available in `standalone-dev` image.

It would be nice to be able to override the host without any extra actions.

**Comment by ruseinov** [comment]
I'm happy to contribute, just not sure where this image is coming from :/

**Comment by ruseinov** [comment]
Was not sure where to put this issue, so closing it in hopes that we can discuss this here.

**Comment by tylertreat** [comment]
@ruseinov Can you open an issue on the https://github.com/liftbridge-io/liftbridge repo? The `dev-standalone` image is built here: https://github.com/liftbridge-io/liftbridge/tree/master/docker/dev-standalone

**Comment by ruseinov** [comment]
Done!
