### ISSUE TITLE
Implement FetchPartitionMetadata

### ISSUE THREAD

**Issue by LaPetiteSouris** [liftbridge-io/go-liftbridge#87]
Resolved issue https://github.com/liftbridge-io/liftbridge/issues/111 provides the necessary  API to fetch `PartitionMetadata` of a particular partition. 

The client should implements this features. 

Changes required:

1. Query and store leader of the given partition, refer to [client implementation guide](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/client_implementation.md#fetchpartitionmetadata)

2. Perform the RPC call

**Comment by LaPetiteSouris** [comment]
For this request, the leader node of each partition is usually given in the [`Metadata` ] (https://github.com/liftbridge-io/go-liftbridge/blob/aa1060c4f76df2d7c2b4d7c5b55119d5057ee318/metadata.go#L36)

Thus when a request is made, we can search the cache for the leader of the partition. If the request is sent and got refused with an error because the receiving is not the partition's leader, the cache should be refreshed.

I am still thinking, should we:

1. Make it simple, when error is found, simply refreshed all `Metadata` cache. This approach is "stupidly" simple and it works well if we do not have too many partitions to manage. It would be tricky to manage too many partitions and refresh all the cache frequently

2. Cache partitions data serparately , thus when we need to refresh the cache of the one partition, we would not have to refresh everything. This approache is optimized, would require more work and do not keep things simple.

Any thoughts are welcomed.

**Comment by tylertreat** [comment]
@LaPetiteSouris You can use the new [`doResilientLeaderRPC`](https://github.com/liftbridge-io/go-liftbridge/blob/aa1060c4f76df2d7c2b4d7c5b55119d5057ee318/v2/client.go#L1563-L1598) to handle making the request to the leader and refreshing metadata. Though looking at the current implementation of that, it just occurred to me it also needs to handle and refresh/retry on the `FailedPrecondition` gRPC error which is returned when the server is not the leader.

**Comment by LaPetiteSouris** [comment]
> @LaPetiteSouris You can use the new [`doResilientLeaderRPC`](https://github.com/liftbridge-io/go-liftbridge/blob/aa1060c4f76df2d7c2b4d7c5b55119d5057ee318/v2/client.go#L1563-L1598) to handle making the request to the leader and refreshing metadata. Though looking at the current implementation of that, it just occurred to me it also needs to handle and refresh/retry on the `FailedPrecondition` gRPC error which is returned when the server is not the leader.

Amazing. That saves me a lot of time actually.

Still, in case of `FailedPrecondition`, I was more into the solution of just refresh the `Metadata` cache . It may sounds like too much to refresh every time, but otherwise we would have to keep partition cache separately. And potentially, making things complicate  would seem to solve a problem that my not exist in the first place:  Do we really have a lot of case when `FailedPrecondition` is raised ?

**Comment by tylertreat** [comment]
IMO the following code in `doResilientLeaderRPC` should be changed from:

```go
if status.Code(err) == codes.Unavailable {
	time.Sleep(50 * time.Millisecond)
	c.metadata.update(ctx)
	continue
}
```

To this:

```go
if code := status.Code(err); code == codes.Unavailable || code == codes.FailedPrecondition {
	time.Sleep(50 * time.Millisecond)
	c.metadata.update(ctx)
	continue
}
```

This will handle the case where the metadata is stale but also `doResilientLeaderRPC` will only attempt this up to 5 times before failing the RPC.

**Comment by LaPetiteSouris** [comment]
> To this:
> 
> ```go
> if code := status.Code(err); code == codes.Unavailable || code == codes.FailedPrecondition {
> 	time.Sleep(50 * time.Millisecond)
> 	c.metadata.update(ctx)
> 	continue
> }
> ```
> 
> This will handle the case where the metadata is stale but also `doResilientLeaderRPC` will only attempt this up to 5 times before failing the RPC.

That's what I think. Will do the implementation and see how it goes.

Still, I just feel that refreshing all cache `metadata` is quite heavy. For now it seems we do not have other choice. But should we somehow improve the cache management in the future ?  E.g: do a "smarter" cache management which goes down to decompose cache into several separate sections that can be refreshed independently ?

**Comment by tylertreat** [comment]
The `FetchMetadata` endpoint actually supports only fetching metadata for specific streams rather than _all_ streams (see [here](https://github.com/liftbridge-io/liftbridge-api/blob/d603f70cc6a16a751d9e6d5f8ecd0f2207c155d3/api.proto#L104)), so we could make it smarter. In the case of `doResilientLeaderRPC`, we really only need to update metadata for the provided stream.

**Comment by LaPetiteSouris** [comment]
closed by https://github.com/liftbridge-io/go-liftbridge/pull/90
