### ISSUE TITLE
Loadbalance publications on multiple brokers

### ISSUE THREAD

**Issue by Jmgr** [liftbridge-io/go-liftbridge#99]
We have performed some load tests where we have published 3000 messages per second on 30 streams on a 3-instance Liftbridge cluster using a single connection. We were wondering why the CPU load and memory usage was not distributed across the Liftbridge instances, but concentrated on one of them.

![lb-cpu](https://user-images.githubusercontent.com/984518/100448462-39f71600-30aa-11eb-8074-2a8773ac10f4.png)

![lb-mem](https://user-images.githubusercontent.com/984518/100448464-3bc0d980-30aa-11eb-8430-7600f3aacbf6.png)

After profiling, we found out that it must be the GRPC processing that triggers this:
![lb-grpc-load](https://user-images.githubusercontent.com/984518/100448787-c1448980-30aa-11eb-920d-360add8b7555.png)

Comparing this with one of the other instances:
![lb-regular-load](https://user-images.githubusercontent.com/984518/100448793-c3a6e380-30aa-11eb-9bd8-e3a28854d424.png)

Could it be possible to add an option to the Liftbridge client to dispatch publication requests to all brokers, using the stream name and partition id as a key so that the per-partition ordering is kept? (i.e. consistent hashing) The Liftbridge client would then maintain a connection to all brokers instead of only choosing one of them randomly.

**Comment by tylertreat** [comment]
Yes, this makes sense to me. Maintaining a single connection to each broker would also greatly simplify the current connection pool logic, though I'm not sure what the performance impact would be reusing the same connection across multiple publishes, subscriptions, etc.

Somewhat related, I'd like to eventually get go-liftbridge to use gRPC's `Resolver` and `Picker` interfaces for establishing connections rather than custom logic (see https://github.com/liftbridge-io/go-liftbridge/issues/89).

**Comment by Jmgr** [comment]
> Somewhat related, I'd like to eventually get go-liftbridge to use gRPC's `Resolver` and `Picker` interfaces for establishing connections rather than custom logic (see #89).

That makes sense. Both are flagged as being experimental though, wouldn't that be an issue?

**Comment by tylertreat** [comment]
> Both are flagged as being experimental though, wouldn't that be an issue?

I think it's only an issue if we expose those details to the user through the API, but I'm imagining this being an implementation detail of the library, just like the current connection logic.
